### ISSUE TITLE
plugin failed to load

### ISSUE THREAD

**Issue by manmaed** [blink-dev/tempMute#1]
Plugin Failed to load api version not compatible need 26 got 23
![](https://ss.manmaed.net/1688320118.png)

**Comment by blink-dev** [comment]
No way someone still use this plugin 😄 
Need to download build tools to recompile for new API

**Comment by blink-dev** [comment]
Done
You can wait for update to come to myTeamspeak
or you can download new release now from [Releases](https://github.com/blink-dev/tempMute/releases)

**Comment by manmaed** [comment]
i can now sneeze in peace and not blow people's ears out thanks :D
